services:
  postgres-db:
    image: postgres:17.2
    container_name: ${CONTAINER_NAME:-postgres-db}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-moodyUser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SuperSecretPassword123}
      POSTGRES_DB: ${POSTGRES_DB:-moodboard}
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - moodboard-net
    restart: always

volumes:
  postgres-data:

networks:
  moodboard-net:
    driver: bridge
