name: Build and Deploy IaC with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit:ci

      - name: Set up AWS CLI
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Infrastructure with CDK
        if: github.ref == 'refs/heads/main'
        working-directory: ./iac
        run: |
          npm install
          npm run cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/us-east-1
          npm run deploy:ci
