name: Build and Deploy MoodStack with Docker

on:
  push:
    branches:
      - iac-improvements
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install Dependencies
      #   run: npm install

      # - name: Unit tests
      #   run: npm run test:unit:ci

      # - name: Linting
      #   run: npm run lint

      # - name: Build
      #   run: npm run build

      - name: Set up AWS CLI
        if: github.ref == 'refs/heads/iac-improvements'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Infrastructure with CDK
        if: github.ref == 'refs/heads/iac-improvements'
        working-directory: ./iac
        run: |
          npm install
          npm run cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/us-east-1
          npm run deploy:ci
